sudo: required
language: c
os:
  - linux
  - osx

install:
  - git clone --branch=master https://github.com/waruqi/xmake.git waruqi/xmake
  - cd ./waruqi/xmake
  - ./install
  - cd -

script:
  - xmake  
  - xmake f -m debug
  - xmake 
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      xmake f -p iphoneos;
      xmake;
      xmake f -m debug;
      xmake; 
      xmake f -a arm64;
      xmake;
      xmake f -m debug;
      xmake;
      xmake f -p iphonesimulator;
      xmake;
      xmake f -m debug;
      xmake; 
    fi
