sudo: required
language: C
os:
  - linux
  - osx

install:
  - git clone --branch=master https://github.com/waruqi/xmake.git waruqi/xmake
  - cd ./waruqi/xmake
  - ./install
  - cd -

script:
  - xmake  
  - xmake f -m debug
  - xmake -j 4
  - xmake p
  - xmake c
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      xmake f -p iphoneos;
      xmake;
      xmake f -m debug;
      xmake -j 4;
      xmake p -a "armv7,armv7s,arm64";
      xmake f -p iphonesimulator;
      xmake;
      xmake f -m debug;
      xmake -j 4; 
    fi
