language: generic

cache:
  directories:
    - /tmp/tools

before_install:
  - git clone git@github.com:waruqi/xmake.git /tmp/tools
  - chmod -R 777 /tmp/tools/xmake
  - /tmp/tools/xmake/install

install:
  - /tmp/tools/cmake --prefix="$HOME" --exclude-subdir

before_script :
  - xmake f

script:
  - xmake r
