sudo: required
language: C
os:
  - linux
  - osx

install:
  - git clone --branch=master https://github.com/waruqi/xmake.git waruqi/xmake
  - cd ./waruqi/xmake
  - sudo ./install
  - cd -
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      git clone https://github.com/linux-test-project/lcov.git;
      sudo make -C ./lcov install;
      gem install coveralls-lcov;
    fi

script:
  - xmake 
  - xmake r demo
  - xmake f -m debug
  - xmake -j 4
  - xmake r demo
  - xmake p
  - xmake c
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      xmake f -m profile;
      xmake;
      xmake f -m coverage;
      xmake; 
      xmake r demo;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      xmake f -p iphoneos;
      xmake;
      xmake f -m debug;
      xmake -j 4;
      xmake p -a "armv7,armv7s,arm64";
      xmake f -p iphonesimulator;
      xmake;
      xmake f -m debug;
      xmake -j 4; 
    fi

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      lcov --directory ./src/tbox --capture --output-file coverage.info;
      lcov --list coverage.info;
      coveralls-lcov --repo-token ET46Ov7RFtlE1YB13eVq0fWtJg1iY9dXx coverage.info;
    fi
