sudo: required
language: c

install:
  - git clone --branch=master https://github.com/waruqi/xmake.git waruqi/xmake
  - cd ./waruqi/xmake
  - ./install
  - cd -

before_script :
  - xmake f -c

script:
  - xmake -r
