language: c

cache:
  directories:
    - /tmp/tools

install:
  - git clone git@github.com:waruqi/xmake.git /tmp/tools
  - chmod -R 777 /tmp/tools/xmake
  - /tmp/tools/xmake/install

before_script :
  - xmake f

script:
  - xmake r
