sudo: required
language: C
os:
  - linux
  - osx

install:
  - git clone --branch=master https://github.com/waruqi/xmake.git waruqi/xmake
  - cd ./waruqi/xmake
  - sudo ./install
  - cd -
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      git clone https://github.com/linux-test-project/lcov.git;
      sudo make -C ./lcov install;
      gem install coveralls-lcov;
    fi

script:
  - xmake 
  - xmake r demo
  - xmake f -m debug
  - xmake -j 4
  - xmake r demo
  - xmake p
  - xmake c
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      xmake f -m profile;
      xmake -r -j 4;
      xmake f -m coverage;
      xmake -r -j 4;
      xmake r demo stream http://tboox.net /tmp/a;
      xmake r demo stream_async_stream http://www.tboox.org /tmp/a;
      xmake r demo regex;
      xmake r demo network_url;
      xmake r demo network_cookies;
      xmake r demo libm_float;
      xmake r demo libm_double;
      xmake r demo math_fixed;
      xmake r demo libc_time;
      xmake r demo libc_wchar;
      xmake r demo libc_stdlib;
      xmake r demo libc_string;
      xmake r demo algorithm_find;
      xmake r demo algorithm_sort;
      xmake r demo container_list;
      xmake r demo container_heap;
      xmake r demo container_queue;
      xmake r demo container_vector;
      xmake r demo container_hash_map;
      xmake r demo object_dump ./res/object.xml;
      xmake r demo object_dump ./res/object.bin;
      xmake r demo object_dump ./res/object.json;
      xmake r demo object_dump ./res/object.bplist;
      xmake r demo object_dump ./res/object.xplist;
      xmake r demo database_sql /tmp/sqlite3.db;
      xmake r demo utils_dump /tmp/sqlite3.db;
      xmake r demo utils_crc hello;
      xmake r demo utils_md5 hello;
      xmake r demo utils_sha hello;
      xmake r demo utils_bits;
      xmake r demo platform_ifaddrs;
      xmake r demo platform_hostname;
      xmake r demo platform_backtrace;
      xmake r demo platform_thread_pool;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      xmake f -p iphoneos;
      xmake;
      xmake f -m debug;
      xmake -r -j 4;
      xmake p -a "armv7,armv7s,arm64";
      xmake f -p iphonesimulator;
      xmake -r -j 4;
      xmake f -m debug;
      xmake -j 4; 
    fi

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      lcov --directory . --capture --output-file coverage.info;
      lcov --remove coverage.info 'src/demo/*' '/usr/*' --output-file coverage.info;
      lcov --list coverage.info;
      coveralls-lcov --repo-token ET46Ov7RFtlE1YB13eVq0fWtJg1iY9dXx coverage.info;
    fi
